inferno/extensions/optimizers/__init__.py, inferno/extensions/optimizers/adam.py, inferno/extensions/optimizers/adam_L1L2.py, inferno/extensions/optimizers/annealed_adam.py, inferno/io/volumetric/volume.py, tests/training/basic.py, tests/training/callbacks/logging/tensorboard.py
The new optimizer can handle L1 and L2 penalties. AnnealedAdam now inherits from this optimizer.
=> New optimizer for L1 and L2 penalty

inferno/trainers/basic.py, inferno/trainers/callbacks/logging/tensorboard.py, tests/training/callbacks/logging/tensorboard.py
=> Fix Tensorboard

inferno/io/transform/image.py
Added binary dilation and erosion as prepro transforms.
=> Binary morphology transforms for images

inferno/io/transform/base.py
Also uniform syntax for calling volume_function, etc.
=> Enable keyword parameters in Transformation.__call__

inferno/trainers/basic.py
To keep the symmetry with pytorch's cuda()/cpu()
=> enable transfer of model to cpu

inferno/extensions/containers/graph.py
This PR addresses #3. The second solution was selected.
=> Fix Graph API

HISTORY.rst, inferno/__init__.py, setup.cfg, setup.py
critical bugfix in setup.py install
=> critical bugfix in setup.py install

inferno/io/box/cifar.py
Optional creation of a separate validation set from the training data  for C10/C100
=> Allow for validation set creation in the cifar setting

inferno/trainers/callbacks/logging/base.py
create intermediate log directories as well (missed in #77 that did the same for save directories)
=> create intermediate log directories

inferno/trainers/basic.py
Logic fix for save_now.
See discussion here https://github.com/inferno-pytorch/inferno/issues/99
Cheers!
=> Fix save_now

inferno/extensions/initializers/presets.py, inferno/io/box/camvid.py, inferno/trainers/basic.py, inferno/utils/torch_utils.py, setup.py
Merging several PRs (since there are several fixes)
https://github.com/inferno-pytorch/inferno/pull/107
https://github.com/inferno-pytorch/inferno/pull/106
https://github.com/inferno-pytorch/inferno/pull/105
https://github.com/inferno-pytorch/inferno/pull/102
=> Several changes

inferno/io/box/camvid.py
Fix for the torchvision import error. Tries original import and has a fallback.
=> fix torchvision import error

inferno/trainers/basic.py
Switch back to old-school format for 3.5 people
=> Remove f-string

inferno/extensions/criteria/set_similarity_measures.py, tests/extensions/criteria/set_similarity_measures.py
Added generalized dice loss for multiple classes
=> Added generalized dice loss

inferno/trainers/basic.py, inferno/trainers/callbacks/__init__.py, inferno/trainers/callbacks/base.py, inferno/trainers/callbacks/console.py, inferno/trainers/callbacks/essentials.py, inferno/trainers/callbacks/scheduling.py, inferno/trainers/callbacks/tqdm.py, inferno/trainers/callbacks/tqdmstub.py, inferno/utils/python_utils.py
Enabled via trainer.register_callback(inferno.trainers.callbacks.TQDMProgressBar())
=> Add support for terminal progress bars via TQDM

.travis.yml
Testing running travis on 2 pythons and 2 pytorches.
=> Expand CI Matrix

inferno/trainers/basic.py
Changes are needed to get the batch size when having multiple targets
=> validate with a list of targets

examples/regularized_mnist.py
Docstring from example file `regularized_mnist.py`
=> regularized_mnist.py docstring

inferno/io/volumetric/lazy_volume_loader.py, inferno/io/volumetric/volume.py, tests/io/volumetric/lazy_volume_loader.py
- implement lazy data loader base classes
- implement lazy loader for hdf5, n5 and zarr
- add tests for lazy hdf5 loader
=> Implement lazy data loader

inferno/trainers/callbacks/essentials.py
Quick upgrade to `NaNDetector` to catch NaN, +Inf, and -Inf instead of just NaN.
Cheers
=> Use isfinite instead of isnan

README.rst
It was linking to the wrong badge.
=> Fix travis badge

inferno/trainers/basic.py
- Add option to set the `retain_graph` option of the backward pass to true (false by default).
=> Retain graph

examples/plot_unet_tutorial.py, inferno/extensions/containers/graph.py, inferno/extensions/layers/__init__.py, inferno/extensions/layers/identity.py, inferno/extensions/layers/res_unet.py, inferno/extensions/layers/sampling.py, inferno/extensions/layers/unet_base.py, tests/extensions/layers/unet.py
=> unet cleanup

inferno/trainers/basic.py
Sorry, for the typo in the previous PR. Hope, now it should work
=> FIX: typo with pickle_module name

inferno/io/transform/image.py
Fix wrong order of dimensions for consistence with `RandomCrop`.
=> RandomCrop: Dimension order

.travis.yml, inferno/extensions/containers/graph.py
Fixes #158.
This should fix inferno for networkx versions >= 2.
=> Change networkx API.

examples/plot_cheap_unet.py, inferno/extensions/models/unet.py
- replaced ```nn.Upsample``` with  ```inferno.extensions.layers.sampling.Upsample```
- changed   index in examples ```downsample_op_factory``` from  wrong / not yet changed ```depth-1``` to ```0```
- added an unet example with depthwise convolutions which is fast enough to give ok-ish results with only a CPU in a few seconds
=> minor unet changes, added more examples

inferno/utils/python_utils.py
This allows inferno to be run in a subthread.
from the [docs](https://docs.python.org/3.7/library/signal.html):
> Python signal handlers are always executed in the main Python thread, even if the signal was received in another thread.
=> delay keyboard interrupt only if running in main thread

.travis.yml, docs/usage.rst, inferno/extensions/containers/graph.py, inferno/extensions/criteria/elementwise_measures.py, inferno/extensions/criteria/set_similarity_measures.py, inferno/extensions/initializers/presets.py, inferno/trainers/basic.py, inferno/utils/model_utils.py, inferno/utils/torch_utils.py, tests/test_extensions/test_containers/test_graph.py, tests/test_extensions/test_criteria/test_core.py, tests/test_extensions/test_criteria/test_elementwise_measures.py, tests/test_extensions/test_criteria/test_set_similarity_measures.py, tests/test_extensions/test_layers/deprecated/building_blocks.py, tests/test_extensions/test_layers/test_activations.py, tests/test_extensions/test_layers/test_device.py, tests/test_extensions/test_layers/test_reshape.py, tests/test_training/test_callbacks/test_logging/test_tensorboard.py
Remove deprecated torch.autograd.Variable
Fixes #174. Fixes #179.
=> Remove variable

.travis.yml
remove pytorch 0.4 from travis
=> changed ci script to drop 0.4 tests
